// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH378ngOisc0XC2ZVEwkUbKu8FW1Q4Tvg',
    appId: '1:58454763639:web:685a6e27f69c4999c97e72',
    messagingSenderId: '58454763639',
    projectId: 'sportignite-88208',
    authDomain: 'sportignite-88208.firebaseapp.com',
    storageBucket: 'sportignite-88208.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcz21UuyhyqvWcrwWhodRSeRR6jDAP_o4',
    appId: '1:58454763639:android:c74560dfdc5be807c97e72',
    messagingSenderId: '58454763639',
    projectId: 'sportignite-88208',
    storageBucket: 'sportignite-88208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY4Bie2IBFH99xiY-9OWc8B-Ml8bhRKOo',
    appId: '1:58454763639:ios:e54a84fe5b5f649dc97e72',
    messagingSenderId: '58454763639',
    projectId: 'sportignite-88208',
    storageBucket: 'sportignite-88208.firebasestorage.app',
    iosBundleId: 'com.example.sportIgnite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY4Bie2IBFH99xiY-9OWc8B-Ml8bhRKOo',
    appId: '1:58454763639:ios:e54a84fe5b5f649dc97e72',
    messagingSenderId: '58454763639',
    projectId: 'sportignite-88208',
    storageBucket: 'sportignite-88208.firebasestorage.app',
    iosBundleId: 'com.example.sportIgnite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH378ngOisc0XC2ZVEwkUbKu8FW1Q4Tvg',
    appId: '1:58454763639:web:e10ddde35dd01932c97e72',
    messagingSenderId: '58454763639',
    projectId: 'sportignite-88208',
    authDomain: 'sportignite-88208.firebaseapp.com',
    storageBucket: 'sportignite-88208.firebasestorage.app',
  );
}
